apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
jobs:
  job1:
    uses: .cloudbees/workflows/deployer.yaml
    with:
      environment: ${{ inputs.manifest }}
      manifest: ${{ inputs.manifest }}
